FROM node as builder

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY tsconfig.json package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM node:slim

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json yarn.lock ./

RUN yarn install --production --frozen-lockfile

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 3000
EXPOSE 80
CMD [ "node", "dist/controller.js" ]
