apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: checkstatus-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: amiok.io/v1alpha1
    resource: checkstatuses
  childResources:
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://checkstatus-controller/check
