apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkstatus-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkstatus-controller
  template:
    metadata:
      labels:
        app: checkstatus-controller
    spec:
      containers:
      - name: controller
        image: kimaharfi/amiok-controller:0.0.10
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "80"
          - name: INTERVAL_IMAGE
            value: "kimaharfi/amiok-interval:0.0.4"
          - name: PLATFORM_BASE_URL
            value: "http://81e1f5de694c.ngrok.io"
          - name: PLATFORM_POLLING_INTERVAL_SECS
            value: "10"
        ports:
          - containerPort: 80
            name: controller
---
apiVersion: v1
kind: Service
metadata:
  name: checkstatus-controller
spec:
  selector:
    app: checkstatus-controller
  ports:
  - port: 80

