apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: checkstatuses.amiok.io
spec:
  group: amiok.io
  names:
    kind: CheckStatus
    plural: checkstatuses
    singular: checkstatus
    shortNames:
    - shcs
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status of the check
      jsonPath: .status.healthy
      name: Healthy
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            x-kubernetes-map-type: atomic
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-map-type: atomic
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
     status: {}


