apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: test-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: amiok.io/v1alpha1
    resource: servicehealthcheckstatuses
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://test-controller.test/check
